### ISSUE TITLE
@types/node should be a devDependcy only?

### ISSUE THREAD

**Issue by tbsmark86** [sports-alliance/sports-lib#57]
Hi, just tryed your code and this seemed strange after installing via npm.

Also it should be "npm install @sports-alliance/sports-lib" in the readme

**Comment by jimmykane** [comment]
Hey hi @tbsmark86 thanks for reporting this. 

The readme file should be updated asap. 

regarding the save vs save-dev I think this explains it: 

https://github.com/Microsoft/types-publisher/issues/81

However, if you think otherwise and there is something I am missing out, that is very likely,  I would be happy to learn :-D

**Comment by jimmykane** [comment]
Sorry for the close, that was done automatic as I tagged and pushed one commit

**Comment by tbsmark86** [comment]
No I don't known anything else - just felt strange to me as an typscript newbie.
